name : Node JS exress ci cd pieline

on:
  push:
    branches: main

jobs:
  builds:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone the repository on the runner
        uses: actions/checkout@v6.0.2
        
      - name: Setup nodeJs
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20
          cache: npm

      - name: Install depedencies
        run: npm ci

      - name: Run tests
        run: echo "No test yet"

  docker:
    runs-on: ubuntu-24.04
    needs: builds

    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express:v1.0.0